language: python
python:
 - "2.7"
# command to install dependencies
install:
 - pip install -r requirements.txt --use-mirrors
script: python scorinator/manage.py test --settings=scorinator.settings.test