---
- hosts: dev-servers
  sudo: yes
  user: root
  vars_files:
    - scorinator_vars.yml
  roles:
    - role: common
      tags:
          - common
    - role: redis
      tags:
          - redis
    - role: workers
      tags:
          - workers
