---
- name: service scorinator start/enable
  action: service name=scorinator state=restarted enabled=yes
- name: service calculator start/enable
  action: service name=calculator state=restarted enabled=yes